### ISSUE TITLE
pip support 

### ISSUE THREAD

**Issue by manu-chroma** [nmoya/whatsapp-parser#12]
Hey, 
I've finally found time to finish the work on making a pip installable package for this project. 

I was hoping for you to test the ``pip package`` locally and get it merged soon. 
There is some meta-data such as author name, email id which is required in ``setup.py`` Then you can edit some of the meta info in ``setup.py`` so we can publish this package on pypi easily.

**Comment by nmoya** [comment]
@manu-chroma Yes, I plan to do this today. I will let you know my progress.

**Comment by manu-chroma** [comment]
Good to hear from you!
let me create a PR, it'll contain all the files and new directory structure for the project. 
you can make changes in the PR itself or after merging  :)

**Comment by nmoya** [comment]
@manu-chroma opened this one: https://github.com/nmoya/whatsapp-parser/pull/16

**Comment by nmoya** [comment]
It's uploaded!
https://pypi.python.org/pypi/whatsapp-parser/1.0.0

I will update the readme file with the new instructions

**Comment by manu-chroma** [comment]
oops. I think one other bug slipped my notice. I'll test and patch it in a few hours. the error is with naming convention of the console entry script. 
ps: pip install works perfectly. 
![image](https://cloud.githubusercontent.com/assets/12952080/22564400/6422511a-e9aa-11e6-9c33-aee42e018a01.png)

**Comment by nmoya** [comment]
Glad that pip install worked!
Blame the reviewer!!

**Comment by nmoya** [comment]
@manu-chroma I added you as a collaborator to the project. Let's keep opening PRs and keep with the reviews, just so we can always stay up to date with the changes.

**Comment by nmoya** [comment]
@manu-chroma I added `master` as a protected branch, so we can't force push to it. PR's going to master will be blocked for review. Since you are also an administrator, you can merge without the review, but it's a good practice to wait for a while.

**Comment by manu-chroma** [comment]
> @manu-chroma I added you as a collaborator to the project. 
I'm glad to help and contribute. 

> Let's keep opening PRs and keep with the reviews, just so we can always stay up to date with the changes. @manu-chroma I added master as a protected branch, so we can't force push to it. PR's going to master will be blocked until review. Since you are also an administrator, you can merge without the review, but it's a good practice to wait for a while.

Sounds alright to me. Opening PR's would be sure that there's code review and only useful code is merged into the master.

**Comment by manu-chroma** [comment]
btw what name would you suggest for the executable i.e. ``<executable name> -h`` 

I'm confused between ``wp_parser`` and ``wp_chat``

**Comment by nmoya** [comment]
I would go with wp_parser so it's consistent with the name of the package
that the user installed

**Comment by manu-chroma** [comment]
sure, I feel the same. 

seems like this one is done now. closing.
