### ISSUE TITLE
Where is the chat.py file

### ISSUE THREAD

**Issue by ezequias** [nmoya/whatsapp-parser#27]
Hello everyone

Where is the chat.py file in a way I could execute the command line?

> python chat.py -f myChat.txt -p WhatsApp -n "Nikolas Moya" -r sleepy yes

**Comment by nmoya** [comment]
The readme is outdated. `chat.py` was renamed to `wp_chat.py`. Is it located here: `whatsapp-parser/wp_parser/wp_chat.py`
