### ISSUE TITLE
What does the -n "Nikolas Moya" parameter means

### ISSUE THREAD

**Issue by ezequias** [nmoya/whatsapp-parser#28]
Hello

I would like to know what does the -n "Nikolas Moya" parameter means.

Is this code operational? I am getting a lot of errors even converting code to python 3.

**Comment by nmoya** [comment]
The `-n` parameter defines the name of the `root` contact of the conversation.

If you have a chat history like this:
```
09/12/2012 17:02:35: UsernameOne: Hello, world.
09/12/2012 17:03:35: UsernameTwo: response Time with media <media omitted>
09/12/2012 17:07:35: UsernameOne: Test messg with response Time????
09/12/2012 17:07:36: UsernameOne: Test messg
```

You should use `-n "UsernameOne"` or `-n "UsernameTwo"`, depending on who you want to be the main contact of the conversation. All messages that are not from the root will be computed as "received". All messages from the root will be computed as "sent"

Again, the readme is outdated. PRs are welcome :-)

Regarding Python 3, this code was made a few years ago using python 2. I never tested migrating it to Python3.
